# Generated by Django 3.1 on 2020-10-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201003_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=300)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
